name: CI

on:
  push:
  pull_request:
    branches:
      - main
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-desktop:
    runs-on: ubuntu-24.04
    container:
      image: bernedom/qtandroidbuilder:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Configure
        run: cmake --preset ci-ninja-desktop-debug

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --output-on-failure
        working-directory: build

  build-android:
    runs-on: ubuntu-24.04
    container:
      image: bernedom/qtandroidbuilder:latest

    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86_64]
        build_type: [debug, release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Configure
        run: cmake --preset ci-ninja-android-${{ matrix.arch }}-${{ matrix.build_type }}

      - name: Build
        run: cmake --build build_android_${{ matrix.arch }}

      - name: sign APK
        if: matrix.build_type == 'release'
        run: |
          echo "${{ secrets.UPLOAD_KEYSTORE_BASE64 }}" | base64 -d > upload-key.jks
          apksigner sign --ks ./upload-key.jks --ks-pass pass:${{ secrets.UPLOAD_KEYSTORE_PASSWORD }} --key-pass pass:${{ secrets.UPLOAD_KEYSTORE_PASSWORD }} ./build_android_${{ matrix.arch }}/QRLiteApp/android-build/QRLite.apk

      - name: Upload APK
        if: matrix.build_type == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ matrix.build_type }}-${{ matrix.arch }}
          path: ./build_android_${{ matrix.arch }}/QRLiteApp/android-build/QRLite.apk
          retention-days: 7

  build-android-bundle:
    runs-on: ubuntu-24.04
    container:
      image: bernedom/qtandroidbuilder:latest

    strategy:
      matrix:
        build_type: [debug, release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Configure arm64-v8a
        run: cmake --preset ci-ninja-android-arm64-v8a-${{ matrix.build_type }}
      - name: build arm64-v8a
        run: cmake --build build_android_arm64-v8a
      - name: Configure x86_64
        run: cmake --preset ci-ninja-android-x86_64-${{ matrix.build_type }}
      - name: build x86_64
        run: cmake --build build_android_x86_64
      
      
      - name: Configure Android App Bundle
        run: /opt/Qt/6.11.1/android_x86_64/bin/qt-cmake --preset ci-ninja-android-all-archs-${{ matrix.build_type }} -DQT_ANDROID_MULTI_ABI_FORWARD_VARS="ANDROID_PLATFORM"
      - name: Build Android App Bundle
        run: cmake --build build_android_bundle --target aab

      - name: Upload AAB artifact
        if: matrix.build_type == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: aab-${{ matrix.build_type }}
          path: ./build_android_bundle/QRLiteApp/android-build/build/outputs/bundle/${{ matrix.build_type }}/android-build-${{ matrix.build_type }}.aab
          retention-days: 7
  
  sign-android-bundle:
    runs-on: ubuntu-24.04
    if: github.event_name == 'release'
    container:
      image: bernedom/qtandroidbuilder:latest

    needs: build-android-bundle

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Download release AAB artifact
        uses: actions/download-artifact@v8
        with:
          name: aab-release

      
      - name: Decode upload key
        run: echo "${{ secrets.UPLOAD_KEYSTORE_BASE64 }}" | base64 -d > upload-key.jks

      - name: Sign Android App Bundle
        run: |
          jarsigner -keystore ./upload-key.jks -storepass '${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}' -keypass '${{ secrets.UPLOAD_KEYSTORE_PASSWORD}}' ./android-build-release.aab ${{ secrets.UPLOAD_KEYSTORE_ALIAS}}

      - name: Verify signature
        run: |
          jarsigner -verify -verbose -certs ./android-build-release.aab

      - name: Upload signed AAB artifact
        uses: actions/upload-artifact@v7
        with:
          name: signed-aab-release
          path: ./android-build-release.aab
          retention-days: 7
      #TODO upload to playstore if release tag